Hw04 auth
Mark4Titan/hw02-express pull request #3
Opened 2022-11-14 10:18 UTC by Mark4Titan

На перевірку

2022-11-14 18:33 UTC, Eastvarga commented on routes/api/auth.js
> +  if (!user) throw new Error("!email");
То Ви дуже змудрували. Для цього є валідайія та помилки валідації, а далі якщо елемент не знайдено, то поганий запит, або не знайдено у відповіді може бути

2022-11-14 18:34 UTC, Eastvarga commented on routes/api/auth.js
> +  const { owner } = await paramsContact(req);
Чи перевіряли ви, працює цей раут чи ні. В мене він завжди не знайдено, помилку повертає. До того ж це дуже ускладнили ви логіку

2022-11-14 18:39 UTC, Eastvarga commented on routes/auth.router.js
> +  tryCatchWrapper(authController.register, errorNotebook)
Не погане рішення, але складне.
Вам треба попрацювати над оптимізацією Ваших логічних послідовностей. Є хист до ускладнення логіки

2022-11-14 18:41 UTC, Eastvarga commented on routes/helpers/params.js
> +  const result = await {
О це ой як зайва незрозуміла конструкція

2022-11-14 18:45 UTC, Eastvarga requested changes
Є зауваження, треба їх усунути

2022-11-17 08:22 UTC, Mark4Titan commented on routes/api/auth.js
> +  const { owner } = await paramsContact(req);
функцію перевірив повторно, усе працює

2022-11-17 08:23 UTC, Mark4Titan commented on routes/api/auth.js
> +  if (!user) throw new Error("!email");
регресував обробку

2022-11-17 08:25 UTC, Mark4Titan commented on routes/auth.router.js
> +  tryCatchWrapper(authController.register, errorNotebook)
не розумію що може бути простіше, писати усе в одній функції, тоді буде тіль перевіряти простіше, а от працювати, точно ні

2022-11-17 08:25 UTC, Mark4Titan commented on routes/helpers/params.js
> +  const result = await {
поправив

2022-11-17 15:21 UTC, Eastvarga commented on routes/api/auth.js
> +  await user.save();
Що буде коли юзер повторно буде реєструватись? Як Ви вирішили цей кейс?

2022-11-17 15:23 UTC, Eastvarga commented on routes/api/auth.js
> +  const { error } = authSchema.validate(req.body);
Валідацію краще винести до мідлвара перед сервісом. Принцип розподілення відповідальності дуже важливий.

2022-11-17 15:26 UTC, Eastvarga commented on routes/api/auth.js
> +  if (!passwordDidNotMatch) throw new Error("!pasword");
Погане ім'я для змінної 
як Ви читаєте вираз [! (не)] passwordDidNotMatch ? Не здається що щось не те? passwordMatch буде як за сутю так і з виразом протиставлення краще сприйматись

2022-11-17 15:31 UTC, Eastvarga requested changes
Є критичне зауваження - не перевіряєте дублювання пошти юзера при реєстрації! Треба виправити

2022-11-18 05:57 UTC, Mark4Titan commented
усе перевіряє, якщо після підключення не дропати "users" в mongoDB. Монго створює схеми яких немає тільки при підключенні до DB.

2022-11-21 20:03 UTC, Eastvarga approved these changes

2022-11-21 20:03 UTC, merged